options:
  logging: CLOUD_LOGGING_ONLY

steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args: [
      'build',
      '-t', 'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/model-api',
      '.'
    ]


  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args: [
      'push',
      'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/model-api'
    ]


  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Cloud Run
    args: [
      'run',
      'deploy',
      'mentalq-model-api',
      '--image',
      'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/model-api',
      '--region',
      'asia-southeast2',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--port=3000',
      '--timeout',
      '600s',
      '--memory',
      '4Gi',
    ]

images:
  - 'asia-southeast2-docker.pkg.dev/mentalq-cloud/mentalq-backend/model-api'
